/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/6MvzYDm9vAIKrX09/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#0071a1']} />
      <group {...props} dispose={null}>
        <mesh
          name="Sphere 8"
          geometry={nodes['Sphere 8'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[-31.42, -225.99, 104.46]}
          rotation={[-Math.PI, -1.31, 0.44]}
          scale={1}
        />
        <mesh
          name="Sphere 7"
          geometry={nodes['Sphere 7'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[-184.9, 71.84, -152.11]}
          rotation={[1.61, -0.16, 2.27]}
          scale={1}
        />
        <mesh
          name="Sphere 6"
          geometry={nodes['Sphere 6'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[-239.15, -63.64, 37.2]}
          rotation={[0.45, 0.14, 1.64]}
          scale={1}
        />
        <mesh
          name="Sphere 5"
          geometry={nodes['Sphere 5'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[132.07, -96.8, 213.49]}
          rotation={[2.06, -0.05, -0.54]}
          scale={1}
        />
        <mesh
          name="Sphere 4"
          geometry={nodes['Sphere 4'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[-41.37, -149.23, -195.26]}
          rotation={[2.51, 1.4, 1.41]}
          scale={1}
        />
        <mesh
          name="Sphere 3"
          geometry={nodes['Sphere 3'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[-154.43, 53.42, 178.08]}
          rotation={[0, 0.91, 1.27]}
        />
        <mesh
          name="Sphere 9"
          geometry={nodes['Sphere 9'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[188.34, -64.11, -135.2]}
          rotation={[-0.3, 0.61, -1.52]}
          scale={1}
        />
        <mesh
          name="Sphere 10"
          geometry={nodes['Sphere 10'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[1.93, 145.13, -191.36]}
          rotation={[-0.77, -0.91, 0.04]}
          scale={1}
        />
        <mesh
          name="Sphere 14"
          geometry={nodes['Sphere 14'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[145.71, 71.48, 154.11]}
          rotation={[-1.28, -0.71, -2.09]}
          scale={1}
        />
        <mesh
          name="Sphere 11"
          geometry={nodes['Sphere 11'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[216.63, 105.82, 28.38]}
          rotation={[-1.14, -0.48, -1.48]}
          scale={1}
        />
        <mesh
          name="Sphere 13"
          geometry={nodes['Sphere 13'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[49.17, 164.06, 146.84]}
          rotation={[0.79, 0.58, -0.2]}
          scale={1}
        />
        <mesh
          name="Sphere 12"
          geometry={nodes['Sphere 12'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[-142.31, 171.26, 8.29]}
          rotation={[-0.25, 0.34, 0.53]}
          scale={1}
        />
        <mesh
          name="Sphere 2"
          geometry={nodes['Sphere 2'].geometry}
          material={materials['MIDDLE Spheres']}
          castShadow
          receiveShadow
          position={[68.48, 220.28, -3.2]}
          rotation={[-0.77, -0.91, -0.87]}
          scale={1}
        />
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials['Sphere Material']}
          castShadow
          receiveShadow
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          far={100000}
          near={-100000}
          position={[-314.31, 222.66, 923.19]}
          rotation={[-0.23, -0.33, -0.08]}
          scale={1}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
